/** MDXEditor 4.2.3 documented translation hook; editor content is never translated. */
const messages: Readonly<Record<string, string>> = {
  "contentArea.editableMarkdown": "可编辑的 Markdown",
  "codeBlock.selectLanguage": "选择代码块语言",
  "codeBlock.inlineLanguage": "语言",
  "codeblock.delete": "删除代码块",
  "frontmatterEditor.title": "编辑文档元信息",
  "frontmatterEditor.key": "键",
  "frontmatterEditor.value": "值",
  "frontmatterEditor.addEntry": "添加条目",
  "dialogControls.save": "保存",
  "dialogControls.cancel": "取消",
  "imageEditor.deleteImage": "删除图片",
  "imageEditor.editImage": "编辑图片",
  "uploadImage.dialogTitle": "上传图片",
  "uploadImage.uploadInstructions": "从设备上传图片：",
  "uploadImage.addViaUrlInstructions": "或通过网址添加图片：",
  "uploadImage.addViaUrlInstructionsNoUpload": "通过网址添加图片：",
  "uploadImage.autoCompletePlaceholder": "选择或粘贴图片地址",
  "uploadImage.alt": "替代文本：",
  "uploadImage.title": "标题：",
  "uploadImage.width": "宽度：",
  "uploadImage.height": "高度：",
  "createLink.url": "网址",
  "createLink.urlPlaceholder": "选择或粘贴网址",
  "createLink.textTooltip": "链接显示的文本",
  "createLink.text": "链接文本",
  "createLink.titleTooltip": "悬停时显示的链接标题",
  "createLink.title": "链接标题",
  "createLink.saveTooltip": "设置网址",
  "createLink.cancelTooltip": "取消更改",
  "linkPreview.edit": "编辑链接网址",
  "linkPreview.copyToClipboard": "复制到剪贴板",
  "linkPreview.copied": "已复制！",
  "linkPreview.remove": "移除链接",
  "table.deleteTable": "删除表格",
  "table.columnMenu": "列菜单",
  "table.textAlignment": "文本对齐",
  "table.alignLeft": "左对齐",
  "table.alignCenter": "居中对齐",
  "table.alignRight": "右对齐",
  "table.insertColumnLeft": "在左侧插入一列",
  "table.insertColumnRight": "在右侧插入一列",
  "table.deleteColumn": "删除此列",
  "table.rowMenu": "行菜单",
  "table.insertRowAbove": "在上方插入一行",
  "table.insertRowBelow": "在下方插入一行",
  "table.deleteRow": "删除此行",
  "toolbar.blockTypes.paragraph": "段落",
  "toolbar.blockTypes.quote": "引用",
  "toolbar.blockTypes.heading": "{{level}} 级标题",
  "toolbar.blockTypeSelect.selectBlockTypeTooltip": "选择内容块类型",
  "toolbar.blockTypeSelect.placeholder": "内容块类型",
  "toolbar.bold": "加粗",
  "toolbar.removeBold": "取消加粗",
  "toolbar.italic": "斜体",
  "toolbar.removeItalic": "取消斜体",
  "toolbar.underline": "下划线",
  "toolbar.removeUnderline": "取消下划线",
  "toolbar.strikethrough": "删除线",
  "toolbar.removeStrikethrough": "取消删除线",
  "toolbar.superscript": "上标",
  "toolbar.removeSuperscript": "取消上标",
  "toolbar.subscript": "下标",
  "toolbar.removeSubscript": "取消下标",
  "admonitions.note": "备注",
  "admonitions.tip": "提示",
  "admonitions.danger": "危险",
  "admonitions.info": "信息",
  "admonitions.caution": "注意",
  "admonitions.changeType": "选择提示块类型",
  "admonitions.placeholder": "提示块类型",
  "codeBlock.language": "代码块语言",
  "toolbar.removeInlineCode": "取消代码格式",
  "toolbar.inlineCode": "行内代码格式",
  "toolbar.link": "创建链接",
  "toolbar.richText": "富文本",
  "toolbar.diffMode": "差异模式",
  "toolbar.source": "源码模式",
  "toolbar.removeHighlight": "取消高亮",
  "toolbar.highlight": "高亮",
  "toolbar.admonition": "插入提示块",
  "toolbar.codeBlock": "插入代码块",
  "toolbar.editFrontmatter": "编辑元信息",
  "toolbar.insertFrontmatter": "插入元信息",
  "toolbar.image": "插入图片",
  "toolbar.table": "插入表格",
  "toolbar.thematicBreak": "插入分隔线",
  "toolbar.bulletedList": "无序列表",
  "toolbar.numberedList": "有序列表",
  "toolbar.checkList": "任务清单",
  "toolbar.undo": "撤销 {{shortcut}}",
  "toolbar.redo": "重做 {{shortcut}}",
  "dialog.close": "关闭对话框",
  "toolbar.toggleGroup": "切换分组"
};
export function editorTranslation(key: string, defaultValue: string, interpolations?: Record<string, unknown>): string {
  const message = messages[key] ?? defaultValue;
  return message.replace(/{{\s*([A-Za-z0-9_.-]+)\s*}}/g, (placeholder, name: string) => Object.prototype.hasOwnProperty.call(interpolations ?? {}, name) ? String(interpolations![name]) : placeholder);
}
export const EDITOR_TRANSLATION_KEYS = Object.keys(messages);
